name: Label Merged PRs
on:
  pull_request:
    types: [closed]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is merged
        id: check-merged
        run: echo "::set-output name=merged::${{ github.event.pull_request.merged }}"
      
      - name: Add 'approved' label
        if: steps.check-merged.outputs.merged == 'true'
        uses: actions/labeler@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: Approved
