name: Label Merged PRs

on:
  pull_request:
    types: [closed]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label Merged PRs
        if: github.event.pull_request.merged == true && github.event.pull_request.user.login == 'dependabot[bot]'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['merged']
            })
